allowMissingFormatter = false
excludes = [
    "*.lock",
    "*.patch",
    "package-lock.json",
    "go.mod",
    "go.sum",
    ".gitattributes",
    ".gitignore",
    ".gitmodules",
    ".hgignore",
    ".svnignore",
    "LICENSE",
    ".pre-commit-config.yaml",
    ".github/workflows/check-pre-commit-hooks.yml",
    ".gitattributes",
    "treefmt.toml",
]
walk = "git"

[formatter.nixfmt]
command = "/nix/store/01945jlqwsgq7a9nbw00y0p0x6027yy3-nixfmt-1.2.0/bin/nixfmt"
excludes = []
includes = ["*.nix"]
options = ["--strict"]

[formatter.rustfmt]
command = "/nix/store/9wi5z0im56rqi3j9g8n4dksazifvfbi9-rust-default-1.95.0/bin/rustfmt"
excludes = []
includes = ["*.rs"]
options = ["--config", "skip_children=true", "--edition", "2024"]
