---
name: Ansible CI
on:
  workflow_call:
    inputs:
      collection:
        type: string
        required: true

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint-roles:
    name: "Run ansible-lint (roles)"
    uses: famedly/engineering-standards/.github/workflows/ansible-lint.yml@v1
    with:
      collection: ${{ inputs.collection }}
      target: roles
  lint-playbooks:
    name: "Run ansible-lint (playbooks)"
    uses: famedly/engineering-standards/.github/workflows/ansible-lint.yml@v1
    with:
      collection: ${{ inputs.collection }}
      target: playbooks
  test-units:
    name: "Run unit tests"
    uses: famedly/engineering-standards/.github/workflows/ansible-test.yml@v1
    with:
      testing-type: units
      collection: ${{ inputs.collection }}
  test-sanity:
    name: "Run sanity tests"
    uses: famedly/engineering-standards/.github/workflows/ansible-test.yml@v1
    with:
      testing-type: sanity
      collection: ${{ inputs.collection }}
  test-integration:
    name: "Run integration tests"
    uses: famedly/engineering-standards/.github/workflows/ansible-test.yml@v1
    with:
      testing-type: integration
      collection: ${{ inputs.collection }}
  black:
    name: "Format using black"
    uses: famedly/engineering-standards/.github/workflows/ansible-black.yml@v1
    with:
      collection: ${{ inputs.collection }}
