name: "Deploy review app"

on:
  workflow_call:
    inputs:

      pr:
        description: "The PR number to deploy the review app for"
        type: string
      projectname:
        description: "Project name used in the review app URL"
        type: string
        required: true
      environment:
        type: string
        description: "GitHub environment name"
        required: false
      artifact-name:
        type: string
        default: web
        required: false

permissions:
  contents: read
  deployments: write

jobs:
  deploy_review_app:
    if: ${{ inputs.pr }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: "https://${{ inputs.projectname }}-pr-${{ inputs.pr }}.web-review.famedly.de"
    steps:
      - uses: actions/download-artifact@@downloadArtifact@
        with:
          name: ${{ inputs.artifact-name }}
          path: public

      - name: Deploy to review server
        run: |
          eval $(ssh-agent -s)
          echo '${{ secrets.FRONTEND_REVIEW_APP_SSH_KEY }}' | ssh-add -
          mkdir -p ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
          rsync -av --delete public/ \
            "web-review@web-review.famedly.de:/opt/web-review/web/${{ inputs.projectname }}-pr-${{ inputs.pr }}"
          echo "Review app: [App](https://${{ inputs.projectname }}-pr-${{ inputs.pr }}.web-review.famedly.de)" >> "$GITHUB_STEP_SUMMARY"

  qa_app:
    if: contains(github.ref_name, 'rc')
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: "https://qa-${{ inputs.projectname }}.web-review.famedly.de"
    steps:
      - uses: actions/download-artifact@@downloadArtifact@
        with:
          name: ${{ inputs.artifact-name }}
          path: public

      - name: Deploy QA app
        run: |
          eval $(ssh-agent -s)
          echo '${{ secrets.FRONTEND_REVIEW_APP_SSH_KEY }}' | ssh-add -
          mkdir -p ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
          rsync -av --delete public/ \
            "web-review@web-review.famedly.de:/opt/web-review/web/qa-${{ inputs.projectname }}"
          echo "QA app: [App](https://qa-${{ inputs.projectname }}.web-review.famedly.de)" >> "$GITHUB_STEP_SUMMARY"

  cleanup_review_apps:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up closed PR deployments
        run: |
          eval $(ssh-agent -s)
          echo '${{ secrets.FRONTEND_REVIEW_APP_SSH_KEY }}' | ssh-add -
          mkdir -p ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

          gh api -H "Accept: application/vnd.github+json" \
            "/repos/${{ github.repository }}/deployments?environment=${{ inputs.environment }}" \
            | jq -c 'group_by(.ref) | map({ref: .[0].ref, deployments: map(.id) | join(" ")}) | .[]' > ./deployments

          while IFS= read -r deployment; do
            ref=$(echo "$deployment" | jq -r '.ref')
            gh api --paginate -X GET -H "Accept: application/vnd.github+json" \
              "/repos/${{ github.repository }}/pulls" -f "head=famedly:$ref" -f "state=closed" \
              | jq '.[].number' > ./prs

            while IFS= read -r pr; do
              echo "Deleting review app for PR $pr"
              ssh -n web-review@web-review.famedly.de rm -rf \
                "/opt/web-review/web/${{ inputs.projectname }}-pr-${pr}"
            done < ./prs

            if [ -s ./prs ]; then
              for d in $(echo "$deployment" | jq -r '.deployments'); do
                gh api --method POST -H "Accept: application/vnd.github+json" \
                  "/repos/${{ github.repository }}/deployments/${d}/statuses" -f state='inactive'
                gh api --method DELETE -H "Accept: application/vnd.github+json" \
                  "/repos/${{ github.repository }}/deployments/${d}"
              done
            fi
          done < ./deployments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
