# Central SDK version pins for Dart and Flutter.
#
# These versions are consumed by the Dart/Flutter SDK derivations
# (packages/dart-sdk.nix, packages/flutter-sdk.nix) and are intended to
# guarantee identical SDKs locally (DevShell) and in CI.
#
# DO NOT edit this file by hand. Regenerate it instead:
#   nix run .#updateSdkVersions                    # latest stable of both
#   nix run .#updateSdkVersions -- --dart X.Y.Z    # pin a specific version
#   nix run .#updateSdkVersions -- --flutter X.Y.Z
#
# See packages/update-sdk-versions.py for the version sources.
#
# Hashes are SHA256 SRI (sha256-<base64>) for official upstream binaries.
{
  dart = {
    version = "3.11.1";
    hashes = {
      aarch64-darwin = "sha256-L/UXrBpAcA9Sv0MJ+2TA3Hqq4cTjiSe9uehoAo1rAvk=";
      aarch64-linux = "sha256-F2RclAFLG0ahAOQTW2QjXPnBn5yaP7gUlZroKT816Yw=";
      x86_64-darwin = "sha256-pLTOKT4LZtIysx/E9R9e35MOz1rAc7HvNnco8tH5jS0=";
      x86_64-linux = "sha256-z/uPpK+3d8JjDGYxG/WesDTNPqDH+UrTJuGmLGqpwnI=";
    };
  };

  # Flutter stable does not publish Linux arm64 binaries.
  flutter = {
    version = "3.41.6";
    hashes = {
      aarch64-darwin = "sha256-Faccw3Gr5tr7smf0P83ZtL4mxNXl2/SSg6efWNz5By0=";
      x86_64-darwin = "sha256-BuyDNw06ESwn2QN0lD36v4jmVU8hsy5UPQFY7Mdvi68=";
      x86_64-linux = "sha256-UDs+a301L8pdIbZHTsqVrVRNj8OwU3guq2OjYMf8dWk=";
    };
  };
}
