default_language_version:
  rust: system
repos:
- hooks:
  - description: Run clippy on all targets
    entry: /nix/store/y3gpz4ig3r2f3w8qv3ja7p7xkpbl9s90-rust-default-1.95.0/bin/cargo
      clippy --workspace --all-targets -- -D warnings
    id: clippy
    language: rust
    name: clippy
    pass_filenames: false
    types:
    - rust
  - description: Run rustfmt against all packages
    entry: /nix/store/y3gpz4ig3r2f3w8qv3ja7p7xkpbl9s90-rust-default-1.95.0/bin/cargo
      fmt --all --check
    id: rustfmt
    language: rust
    name: rustfmt
    pass_filenames: false
    types:
    - rust
  - description: Ensures the `Cargo.lock` is up to date
    entry: /nix/store/y3gpz4ig3r2f3w8qv3ja7p7xkpbl9s90-rust-default-1.95.0/bin/cargo
      update --offline --workspace --locked
    files: Cargo\.toml|Cargo\.lock
    id: cargo-lock
    language: rust
    name: cargo-lock
    pass_filenames: false
  repo: local
