#!/usr/bin/env python3
# Update nix/dart/sdk-versions.nix with the correct Dart and Flutter versions.
#
# Usage:
#   nix run .#updateSdkVersions                    # latest stable of both
#   nix run .#updateSdkVersions -- --dart X.Y.Z    # pin a specific Dart
#   nix run .#updateSdkVersions -- --flutter X.Y.Z # pin a specific Flutter
#
# Versions come from the authoritative, machine-readable release-metadata
# endpoints that the Dart and Flutter tooling itself uses:
#
#   Dart:    https://storage.googleapis.com/dart-archive/channels/stable/release/latest/VERSION
#            -> {"date": ..., "version": "X.Y.Z", "revision": ...}
#   Flutter: https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json
#            -> current_release.stable -> matching releases[].version
#
# The script also prefetches the SDK archives for every supported platform
# and records their SHA256 SRI hashes, then rewrites sdk-versions.nix.

import argparse
import json
import subprocess
import urllib.request
from pathlib import Path

# Path of the pin file relative to the repository root. Resolved against
# `git rev-parse --show-toplevel` at runtime so it works both when run from
# a checkout and via `nix run` (where this script lives in the Nix store).
SDK_VERSIONS_RELPATH = "nix/dart/sdk-versions.nix"


def sdk_versions_file() -> Path:
    repo_root = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
    return Path(repo_root) / SDK_VERSIONS_RELPATH

DART_VERSION_URL = (
    "https://storage.googleapis.com/dart-archive/channels/stable/release/latest/VERSION"
)
FLUTTER_RELEASES_URL = (
    "https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json"
)

DART_PLATFORMS = {
    "x86_64-linux": "linux-x64",
    "aarch64-linux": "linux-arm64",
    "x86_64-darwin": "macos-x64",
    "aarch64-darwin": "macos-arm64",
}

FLUTTER_ARCHIVES = {
    "x86_64-linux": ("linux", "flutter_linux_{version}-stable.tar.xz"),
    "x86_64-darwin": ("macos", "flutter_macos_{version}-stable.zip"),
    "aarch64-darwin": ("macos", "flutter_macos_arm64_{version}-stable.zip"),
}


def fetch_json(url: str) -> dict:
    print(f"  Fetching {url}")
    with urllib.request.urlopen(url, timeout=30) as r:
        return json.load(r)


def prefetch_sri(url: str) -> str:
    print(f"  Prefetching {url}")
    result = subprocess.run(
        ["nix-prefetch-url", url, "--type", "sha256"],
        capture_output=True,
        text=True,
        check=True,
    )
    base32 = result.stdout.strip()
    sri = subprocess.run(
        ["nix", "hash", "convert", "--hash-algo", "sha256", "--to", "sri", base32],
        capture_output=True,
        text=True,
        check=True,
    )
    return sri.stdout.strip()


def get_dart_version() -> str:
    return fetch_json(DART_VERSION_URL)["version"]


def get_flutter_version() -> str:
    data = fetch_json(FLUTTER_RELEASES_URL)
    current = data["current_release"]["stable"]
    release = next(r for r in data["releases"] if r["hash"] == current)
    return release["version"]


def dart_hashes(version: str) -> dict[str, str]:
    result = {}
    for nix_sys, archive_suffix in DART_PLATFORMS.items():
        url = (
            f"https://storage.googleapis.com/dart-archive/channels/stable/release"
            f"/{version}/sdk/dartsdk-{archive_suffix}-release.zip"
        )
        result[nix_sys] = prefetch_sri(url)
    return result


def flutter_hashes(version: str) -> dict[str, str]:
    result = {}
    for nix_sys, (os_dir, archive_tpl) in FLUTTER_ARCHIVES.items():
        archive = archive_tpl.format(version=version)
        url = (
            f"https://storage.googleapis.com/flutter_infra_release/releases"
            f"/stable/{os_dir}/{archive}"
        )
        result[nix_sys] = prefetch_sri(url)
    return result


def render_nix(dart_ver: str, dart_h: dict, flutter_ver: str, flutter_h: dict) -> str:
    def hashes_block(h: dict, indent: str = "      ") -> str:
        return "\n".join(f'{indent}{k} = "{v}";' for k, v in sorted(h.items()))

    return f"""\
# Central SDK version pins for Dart and Flutter.
#
# These versions are consumed by the Dart/Flutter SDK derivations
# (packages/dart-sdk.nix, packages/flutter-sdk.nix) and are intended to
# guarantee identical SDKs locally (DevShell) and in CI.
#
# DO NOT edit this file by hand. Regenerate it instead:
#   nix run .#updateSdkVersions                    # latest stable of both
#   nix run .#updateSdkVersions -- --dart X.Y.Z    # pin a specific version
#   nix run .#updateSdkVersions -- --flutter X.Y.Z
#
# See packages/update-sdk-versions.py for the version sources.
#
# Hashes are SHA256 SRI (sha256-<base64>) for official upstream binaries.
{{
  dart = {{
    version = "{dart_ver}";
    hashes = {{
{hashes_block(dart_h)}
    }};
  }};

  # Flutter stable does not publish Linux arm64 binaries.
  flutter = {{
    version = "{flutter_ver}";
    hashes = {{
{hashes_block(flutter_h)}
    }};
  }};
}}
"""


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Update nix/dart/sdk-versions.nix with the correct Dart/Flutter versions."
    )
    parser.add_argument(
        "--dart",
        metavar="X.Y.Z",
        help="Pin a specific Dart version instead of the latest stable.",
    )
    parser.add_argument(
        "--flutter",
        metavar="X.Y.Z",
        help="Pin a specific Flutter version instead of the latest stable.",
    )
    args = parser.parse_args()

    if args.dart:
        dart_ver = args.dart
        print(f"==> Using requested Dart version: {dart_ver}")
    else:
        print("==> Fetching latest Dart stable version...")
        dart_ver = get_dart_version()
        print(f"    Dart: {dart_ver}")

    if args.flutter:
        flutter_ver = args.flutter
        print(f"==> Using requested Flutter version: {flutter_ver}")
    else:
        print("==> Fetching latest Flutter stable version...")
        flutter_ver = get_flutter_version()
        print(f"    Flutter: {flutter_ver}")

    print("==> Prefetching Dart hashes...")
    dart_h = dart_hashes(dart_ver)

    print("==> Prefetching Flutter hashes...")
    flutter_h = flutter_hashes(flutter_ver)

    nix_content = render_nix(dart_ver, dart_h, flutter_ver, flutter_h)
    target = sdk_versions_file()
    target.write_text(nix_content)
    print(f"\n==> Written {target}")
    print(f"    Dart {dart_ver}, Flutter {flutter_ver}")
    print("\nNext: commit the updated sdk-versions.nix.")


if __name__ == "__main__":
    main()
