{ flake-parts-lib, lib, ... }:
let
  inherit (lib) types;
in
{
  options.perSystem = flake-parts-lib.mkPerSystemOption (
    { pkgs, ... }:
    {
      options.filegen = {
        settings = {
          files = lib.mkOption {
            description = ''
              Declare file manipulations to perform in the project directory.

              This is intended to do things like create GitHub workflow files,
              pre-commit hook configuration, or to generate or place other
              miscellaneous configuration files used for development in the
              repository.

              To generate the files, an "app" named `filegen-activate` is created,
              which can be executed with `nix run .#filegen-activate`.

              ---

              Note: This module does *not* attempt to protect against writes to or
              reads from files outside of the repository.

              Trying to protect against this is considered somewhat pointless; At
              the end of the day, you have to trust (or inspect) the flakes whose
              code you execute anyway, as they can simply override what this module
              does. A future version might however still add checks simply to
              prevent mistakes and anti-patterns.
            '';
            default = [ ];

            type = types.listOf (
              types.submodule (
                { config, ... }:
                {
                  options = {
                    type = lib.mkOption {
                      description = ''
                        The type of operation to perform on the given file.

                        Normally, this should be set to `copy`.
                      '';

                      type = types.enum [ "copy" ];
                    };

                    target = lib.mkOption {
                      description = ''
                        The target of the file operation.

                        To create a file in-repo, use `.` as the project root.
                      '';
                      type = types.pathWith { absolute = false; };
                    };

                    source = lib.mkOption {
                      description = ''
                        The source of the file operation.

                        This *can* be a nix store path, potentially created by interpolating a
                        variable.
                      '';
                      type = types.nullOr types.path;
                    };

                    clobber = lib.mkOption {
                      description = ''
                        Whether to backup files that already exist. If true or unset, the files
                        will just be deleted.
                      '';
                      type = types.nullOr types.bool;
                    };

                    permissions = lib.mkOption {
                      description = ''
                        The permissions of the created file.

                        Only the execute bit will be preserved by git, so this should
                        practically always be "600" or "700", but other values are
                        technically possible.
                      '';
                      type = types.str;

                      # Since creating read-only files can cause
                      # issues, and nix store paths are by default
                      # read-only, we cautiously set this to 600 by
                      # default.
                      default = "600";
                    };
                  };
                }
              )
            );
          };
        };

        scripts.activate = lib.mkOption {
          description = ''
            A script that applies the files configured with `filegen.files`.
          '';
          readOnly = true;
          type = types.pathInStore;
        };

        generatedFiles = lib.mkOption {
          description = ''
            The list of generated files.
          '';
          readOnly = true;
          type = types.listOf types.str;
        };
      };
    }
  );

  config.perSystem =
    { pkgs, config, ... }:
    let
      cfg = config.filegen;
      new-manifest = pkgs.writers.writeJSON "filegen-manifest.json" cfg.settings;
    in
    {
      filegen.generatedFiles = map (file: lib.removePrefix "./" file.target) cfg.settings.files;

      filegen.settings.files = [
        {
          # We generate a .gitattributes file, which tells the GitHub diff
          # viewer to ignore any files generated by filegen.
          # We then install this file with filegen
          #
          # The real place to review these files is in the Nix that generates them.
          type = "copy";
          target = ".gitattributes";
          source = pkgs.writeTextFile {
            name = ".gitattributes";
            text = lib.pipe cfg.generatedFiles [
              (map (target: "${target} linguist-generated"))
              lib.concatLines
            ];
          };
        }
      ];

      apps =
        let
          activate = pkgs.writers.writeNuBin "filegen-apply-script" ''
            cd (git rev-parse --show-toplevel)

            for file in (open '${new-manifest}' | $in.files) {
              match $file.type {
                "copy" => {
                  (${lib.getExe' pkgs.coreutils "install"}
                    -D
                    --compare
                    $'--mode=($file.permissions)'
                    (if ($file.clobber | default true) { --backup=none } else { --backup=numbered })
                    $file.source $file.target)
                },
                _ => {
                  print $"Type '($file.type)' for '($file.source)' is currently unsupported"
                  exit 1
                }
              }
            }
          '';
        in
        {
          filegen-activate = {
            program = lib.getExe activate;
            meta = {
              description = "Install files defined by the `filegen` options of this flake";
              package = activate;
            };
          };
        };
    };
}
